{% set name = "tatsu" %}
{% set version = "5.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neogeny/TatSu/archive/v{{ version }}.tar.gz
  sha256: 044089cfc8416f567f30b65825c73225b6caa0efed6e9b9bf9069cd523cfc6e9

build:
  number: 0
  entry_points:
    - tatsu = tatsu:main
    - g2e = tatsu.g2e:main
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - tatsu
    - tatsu.codegen
  commands:
    - pip check
    - tatsu --help
  requires:
    - pip

about:
  home: https://github.com/neogeny/tatsu
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: TatSu takes a grammar in a variation of EBNF as input, and outputs a memoizing PEG/Packrat parser in Python.
  doc_url: https://tatsu.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - marcelotrevisani
