{% set python_min = '3.10' %}
{% set name = "tatsu" %}
{% set version = "5.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neogeny/TatSu/archive/v{{ version }}.tar.gz
  sha256: cb996fe7f2def527df0d1280d9ffee7a3d3110c9fbfeb4803754331412bcf4e1

build:
  number: 1
  entry_points:
    - tatsu = tatsu:main
    - g2e = tatsu.g2e:main
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - tatsu
    - tatsu.codegen
  commands:
    - pip check
    - tatsu --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/neogeny/tatsu
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: TatSu takes a grammar in a variation of EBNF as input, and outputs a memoizing PEG/Packrat parser in Python.
  doc_url: https://tatsu.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - marcelotrevisani
